### ISSUE TITLE
Multiple blank lines cause <p>&nbsp;</p>

### ISSUE THREAD

**Issue by LHSnow** [yuin/goldmark#492]
```
one



two
```

outputs

```
<p>one</p>
<p>&nbsp;</p>
<p>two</p>
```

I would have assumed that extra whitespace in markdown is ignored.

relevant config (in Hugo):
```yml
wrapStandAloneImageWithinParagraph: false
attribute:
  block: true
  title: true
renderer:
  unsafe: true
```
