### ISSUE TITLE
Сonfusion with the HasBlankPreviousLines

### ISSUE THREAD

**Issue by mdigger** [yuin/goldmark#71]
```markdown
test 1

test 2


test 3



test 4
```

```yaml
Document {
    Paragraph {
        RawText: "test 1"
        HasBlankPreviousLines: false
        Text: "test 1"
    }
    Paragraph {
        RawText: "test 2"
        HasBlankPreviousLines: true
        Text: "test 2"
    }
    Paragraph {
        RawText: "test 3"
        HasBlankPreviousLines: false
        Text: "test 3"
    }
    Paragraph {
        RawText: "test 4"
        HasBlankPreviousLines: false
        Text: "test 4"
    }
}
```
